# Generated by Django 5.0.6 on 2024-05-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
